### ISSUE TITLE
Reading using sample code results in: Server could not parse the Url., StatusCode: NotFound

### ISSUE THREAD

**Issue by jcjimenez** [Azure/azure-cosmosdb-spark#104]
When attempting to run something like this:

```
    val configMap = Map(
      CosmosDBConfig.Endpoint -> sys.env("COSMOS_DB_ENDPOINT"),
      CosmosDBConfig.Masterkey -> sys.env("COSMOS_DB_MASTER_KEY"),
      CosmosDBConfig.Database -> "samples",
      CosmosDBConfig.Collection -> "airports",
      CosmosDBConfig.PreferredRegionsList -> "East US2;",
      CosmosDBConfig.SamplingRatio -> "1.0",
      CosmosDBConfig.ConnectionMode -> "Gateway",
      CosmosDBConfig.CachingModeParam -> CosmosDBConfig.DefaultCacheMode.toString
    )
    val cosmosConfig = Config(configMap)
    val airportsCosmos = spark.read.cosmosDB[Airport](cosmosConfig)
    airportsCosmos.show()
```
the connector fails with this:
```
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Server could not parse the Url., StatusCode: NotFound
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.tryLookUp(PartitionKeyRangeCache.java:54)
	... 55 more
Caused by: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Server could not parse the Url., StatusCode: NotFound
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:86)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:33)
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.<init>(ProxyQueryExecutionContext.java:68)
	at com.microsoft.azure.documentdb.internal.query.QueryExecutionContextFactory.createQueryExecutionContext(QueryExecutionContextFactory.java:23)
	at com.microsoft.azure.documentdb.QueryIterable.createQueryExecutionContext(QueryIterable.java:70)
	at com.microsoft.azure.documentdb.QueryIterable.reset(QueryIterable.java:115)
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:57)
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:31)
	at com.microsoft.azure.documentdb.DocumentClient.readPartitionKeyRanges(DocumentClient.java:1677)
	at com.microsoft.azure.documentdb.DocumentQueryClientInternal.readPartitionKeyRanges(DocumentQueryClientInternal.java:32)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getRoutingMapForCollection(PartitionKeyRangeCache.java:105)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.access$000(PartitionKeyRangeCache.java:22)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:52)
	at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:49)
```
this also fails when trying with the equivalent API we use for Python:
```
    val airports = spark.read.format("com.microsoft.azure.cosmosdb.spark").options(configMap).load()
    airports.show()
```

**Comment by jcjimenez** [comment]
I was able to resolve this by adding this key pair to my connection configuration:

```
      CosmosDBConfig.ConnectionMode -> "Gateway"
```

for completeness:

```
      CosmosDBConfig.Endpoint -> sys.env("COSMOS_DB_ENDPOINT"),
      CosmosDBConfig.Masterkey -> sys.env("COSMOS_DB_MASTER_KEY"),
      CosmosDBConfig.Database -> "samples",
      CosmosDBConfig.Collection -> "airports",
      CosmosDBConfig.ConnectionMode -> "Gateway"
```

Please let me know if you would like to close this if ConnectionMode `DirectHttps` is not supported (maybe we need to make `Gateway` the default?)

**Comment by dennyglee** [comment]
Let me check this - at minimum we need to document it, maximum its a bug, eh?!

**Comment by khdang** [comment]
I think this is a bug in the CosmosDB. We may have fixed it together with https://github.com/Azure/azure-cosmosdb-spark/issues/84 or https://github.com/Azure/azure-cosmosdb-spark/issues/93. Let me try to repro and confirm.

**Comment by khdang** [comment]
Yes I've confirmed this issue has been fixed in the latest CosmosDB Java SDK which we will be releasing soon.
