### ISSUE TITLE
Connection timeout causes task failure

### ISSUE THREAD

**Issue by timfpark** [Azure/azure-cosmosdb-spark#117]
It would be great to know about these connection timeouts as a warning, but they should not cause the task to fail.  As an aside, is there a typical root cause for these?

17/08/27 20:34:57 WARN TaskSetManager: Lost task 12.0 in stage 4.0 (TID 110, 10.244.8.7, executor 7): java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: org.apache.http.conn.HttpHostConnectException: Connect to bl4prdddc02-docdb-2.documents.azure.com:15205 [bl4prdddc02-docdb-2.documents.azure.com/191.237.32.44] failed: Connection timed out (Connection timed out)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:86)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:33)
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.<init>(ProxyQueryExecutionContext.java:68)
	at com.microsoft.azure.documentdb.internal.query.QueryExecutionContextFactory.createQueryExecutionContext(QueryExecutionContextFactory.java:23)
	at com.microsoft.azure.documentdb.QueryIterable.createQueryExecutionContext(QueryIterable.java:70)
	at com.microsoft.azure.documentdb.QueryIterable.reset(QueryIterable.java:115)
	at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:57)
	at com.microsoft.azure.documentdb.DocumentClient.queryDocuments(DocumentClient.java:1079)
	at com.microsoft.azure.documentdb.DocumentClient.queryDocuments(DocumentClient.java:1050)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBConnection.queryDocuments(CosmosDBConnection.scala:145)
	at com.microsoft.azure.cosmosdb.spark.rdd.CosmosDBRDDIterator.reader$lzycompute(CosmosDBRDDIterator.scala:118)
	at com.microsoft.azure.cosmosdb.spark.rdd.CosmosDBRDDIterator.reader(CosmosDBRDDIterator.scala:63)
	at com.microsoft.azure.cosmosdb.spark.rdd.CosmosDBRDDIterator.hasNext(CosmosDBRDDIterator.scala:200)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.hasNext(SerDeUtil.scala:117)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:112)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:509)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:333)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
Caused by: com.microsoft.azure.documentdb.DocumentClientException: org.apache.http.conn.HttpHostConnectException: Connect to bl4prdddc02-docdb-2.documents.azure.com:15205 [bl4prdddc02-docdb-2.documents.azure.com/191.237.32.44] failed: Connection timed out (Connection timed out)
	at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.invokeStore(HttpTransportClient.java:114)
	at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.invokeStore(HttpTransportClient.java:128)
	at com.microsoft.azure.documentdb.internal.directconnectivity.TransportClient.invokeResourceOperation(TransportClient.java:12)
	at com.microsoft.azure.documentdb.internal.directconnectivity.StoreReader.readFromStore(StoreReader.java:316)
	at com.microsoft.azure.documentdb.internal.directconnectivity.StoreReader.createStoreReadResult(StoreReader.java:211)
	at com.microsoft.azure.documentdb.internal.directconnectivity.StoreReader.readOneReplica(StoreReader.java:180)
	at com.microsoft.azure.documentdb.internal.directconnectivity.StoreReader.readSession(StoreReader.java:87)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ConsistencyReader.readSession(ConsistencyReader.java:78)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ConsistencyReader.read(ConsistencyReader.java:53)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ReplicatedResourceClient.invoke(ReplicatedResourceClient.java:59)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ServerStoreModel$1.apply(ServerStoreModel.java:84)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeStoreClientRequest(RetryUtility.java:113)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ServerStoreModel.processMessage(ServerStoreModel.java:89)
	at com.microsoft.azure.documentdb.DocumentClient$10.apply(DocumentClient.java:3021)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:58)
	at com.microsoft.azure.documentdb.DocumentClient.doQuery(DocumentClient.java:3027)
	at com.microsoft.azure.documentdb.DocumentQueryClientInternal.doQuery(DocumentQueryClientInternal.java:40)
	at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.executeRequest(AbstractQueryExecutionContext.java:214)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.executeOnce(DefaultQueryExecutionContext.java:137)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.fillBuffer(DefaultQueryExecutionContext.java:101)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:84)
	... 25 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to bl4prdddc02-docdb-2.documents.azure.com:15205 [bl4prdddc02-docdb-2.documents.azure.com/191.237.32.44] failed: Connection timed out (Connection timed out)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.invokeStore(HttpTransportClient.java:105)
	... 45 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 53 more

17/08/27 20:34:57 INFO TaskSetManager: Starting task 12.1 in stage 4.0 (TID 147, 10.244.8.7, executor 7, partition 12, PROCESS_LOCAL, 4783 bytes)

**Comment by timfpark** [comment]
PS.  This, in particular, seems to be an issue I'm exclusively seeing with this host:

bl4prdddc02-docdb-2.documents.azure.com:15205 [bl4prdddc02-docdb-2.documents.azure.com/191.237.32.44

Is it possible there is an issue with it?  I'm seeing my job essentially lock up and then eventually time out.

**Comment by khdang** [comment]
As discussed with timfpark, one work around is to use "ConnectionMode" -> "Gateway". This must be due to the way connections are handled and is likely related to this issue https://github.com/Azure/azure-cosmosdb-spark/issues/89. I'm looking into this.

**Comment by timfpark** [comment]
Just as a little more context, the same Spark job worked great as I tested it with more and more data until seemingly right after my collection had finished an auto split to 41 partitions.  Just FYI in case that is a hint.

**Comment by khdang** [comment]
This could be related to the default small connection pool size of 100. We can try to increase this to a larger number with connectionmaxpoolsize configuration.

**Comment by hoyle1977** [comment]
I met the same problem when inserting documents from Spark. Is the "connectionmaxpoolsize" available now?

**Comment by khdang** [comment]
@hoyle1977 the connectionmaxpoolsize config was introduced in the early version of the connector. You can give it a try.

**Comment by gypsysunny** [comment]
is the workaroud using the default ConnectionPolicy()? since "gateway" is the default connectionmode. but that doesn't work to this issue from my side.

**Comment by nomiero** [comment]
This is now fixed
