### ISSUE TITLE
Querying on multi-partition collection causes 'Request url is invalid.' error.

### ISSUE THREAD

**Issue by Nican** [Azure/azure-cosmosdb-spark#124]
Running `spark.sqlContext.read.cosmosDB(CloudConfig)` on a multi-partition collection causes a  `java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Request url is invalid.` exception. 

Sample code:
```json
%%configure
{ "name":"Playground", 
  "executorMemory": "4G", 
  "executorCores": 4, 
  "numExecutors": 4, 
  "driverCores": 4,
   "jars": ["wasb:///jars/azure-documentdb-1.12.0.jar",
            "wasb:///jars/azure-cosmosdb-spark-0.0.3-SNAPSHOT.jar",
            "wasb:///jars/rxjava-1.3.0.jar",
            "wasb:///jars/azure-documentdb-rx-0.9.0-rc1.jar",
            "wasb:///jars/json-20090211.jar"],
 
  "conf": {
    "spark.jars.packages": "graphframes:graphframes:0.5.0-spark2.1-s_2.11",   
    "spark.jars.excludes": "org.scala-lang:scala-reflect"
   }
}
```
```scala
val baseConfigMap = Map(
"Endpoint" -> "https://xxx.documents.azure.com:443/",
"Masterkey" -> "xxx",
"Database" -> "staging",
"preferredRegions" -> "West US",
"Collection" -> "data", 
"SamplingRatio" -> "1.0"
)
val CloudConfig = Config(baseConfigMap)
val CloudColl = spark.sqlContext.read.cosmosDB(CloudConfig)
```

Exception:
```
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Request url is invalid.
ActivityId: 3a2db52c-c8aa-400a-bb27-c224a00f1e0b, StatusCode: BadRequest
  at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.tryLookUp(PartitionKeyRangeCache.java:56)
  at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getOverlappingRanges(PartitionKeyRangeCache.java:36)
  at com.microsoft.azure.documentdb.internal.routing.RoutingMapProviderHelper.getOverlappingRanges(RoutingMapProviderHelper.java:63)
  at com.microsoft.azure.documentdb.DocumentClient.readPartitionKeyRanges(DocumentClient.java:1781)
  at com.microsoft.azure.cosmosdb.spark.CosmosDBConnection.getAllPartitions(CosmosDBConnection.scala:138)
  at com.microsoft.azure.cosmosdb.spark.partitioner.CosmosDBPartitioner.computePartitions(CosmosDBPartitioner.scala:49)
  at com.microsoft.azure.cosmosdb.spark.rdd.CosmosDBRDD.getPartitions(CosmosDBRDD.scala:53)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.Partitioner$$anonfun$defaultPartitioner$2.apply(Partitioner.scala:66)
  at org.apache.spark.Partitioner$$anonfun$defaultPartitioner$2.apply(Partitioner.scala:66)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:66)
  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$reduceByKey$3.apply(PairRDDFunctions.scala:331)
  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$reduceByKey$3.apply(PairRDDFunctions.scala:331)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.PairRDDFunctions.reduceByKey(PairRDDFunctions.scala:330)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema.schema(CosmosDBSchema.scala:66)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBRelation$$lazySchema$lzycompute(CosmosDBRelation.scala:59)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBRelation$$lazySchema(CosmosDBRelation.scala:44)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation$$anonfun$schema$1.apply(CosmosDBRelation.scala:62)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation$$anonfun$schema$1.apply(CosmosDBRelation.scala:62)
  at scala.Option.getOrElse(Option.scala:121)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation.schema$lzycompute(CosmosDBRelation.scala:62)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation.schema(CosmosDBRelation.scala:62)
  at org.apache.spark.sql.execution.datasources.LogicalRelation.<init>(LogicalRelation.scala:40)
  at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:389)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
  at com.microsoft.azure.cosmosdb.spark.schema.DataFrameReaderFunctions.createDataFrame(DataFrameReaderFunctions.scala:104)
  at com.microsoft.azure.cosmosdb.spark.schema.DataFrameReaderFunctions.createCosmosDBDataFrame(DataFrameReaderFunctions.scala:136)
  at com.microsoft.azure.cosmosdb.spark.schema.DataFrameReaderFunctions.cosmosDB(DataFrameReaderFunctions.scala:60)
  ... 51 elided
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Request url is invalid.
ActivityId: 3a2db52c-c8aa-400a-bb27-c224a00f1e0b, StatusCode: BadRequest
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.tryLookUp(PartitionKeyRangeCache.java:54)
  ... 95 more
Caused by: java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Request url is invalid.
ActivityId: 3a2db52c-c8aa-400a-bb27-c224a00f1e0b, StatusCode: BadRequest
  at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:86)
  at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:33)
  at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.<init>(ProxyQueryExecutionContext.java:68)
  at com.microsoft.azure.documentdb.internal.query.QueryExecutionContextFactory.createQueryExecutionContext(QueryExecutionContextFactory.java:23)
  at com.microsoft.azure.documentdb.QueryIterable.createQueryExecutionContext(QueryIterable.java:70)
  at com.microsoft.azure.documentdb.QueryIterable.reset(QueryIterable.java:115)
  at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:57)
  at com.microsoft.azure.documentdb.QueryIterable.<init>(QueryIterable.java:31)
  at com.microsoft.azure.documentdb.DocumentClient.readPartitionKeyRanges(DocumentClient.java:1678)
  at com.microsoft.azure.documentdb.DocumentQueryClientInternal.readPartitionKeyRanges(DocumentQueryClientInternal.java:32)
  at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.getRoutingMapForCollection(PartitionKeyRangeCache.java:105)
  at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache.access$000(PartitionKeyRangeCache.java:22)
  at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:52)
  at com.microsoft.azure.documentdb.internal.routing.PartitionKeyRangeCache$1.call(PartitionKeyRangeCache.java:49)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  ... 3 more
Caused by: com.microsoft.azure.documentdb.DocumentClientException: Request url is invalid.
ActivityId: 3a2db52c-c8aa-400a-bb27-c224a00f1e0b, StatusCode: BadRequest
  at com.microsoft.azure.documentdb.internal.ErrorUtils.maybeThrowException(ErrorUtils.java:69)
  at com.microsoft.azure.documentdb.internal.GatewayProxy.performGetRequest(GatewayProxy.java:240)
  at com.microsoft.azure.documentdb.internal.GatewayProxy.doReadFeed(GatewayProxy.java:109)
  at com.microsoft.azure.documentdb.internal.GatewayProxy.processMessage(GatewayProxy.java:338)
  at com.microsoft.azure.documentdb.DocumentClient$9.apply(DocumentClient.java:3001)
  at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:58)
  at com.microsoft.azure.documentdb.DocumentClient.doReadFeed(DocumentClient.java:3011)
  at com.microsoft.azure.documentdb.DocumentQueryClientInternal.doReadFeed(DocumentQueryClientInternal.java:36)
  at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.executeRequest(AbstractQueryExecutionContext.java:215)
  at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.executeOnce(DefaultQueryExecutionContext.java:131)
  at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.fillBuffer(DefaultQueryExecutionContext.java:101)
  at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:84)
  ... 17 more
```

Querying collections with only 1 partition works. 

EDIT: Upon further testing, it is not `query_custom` that is broken; It is does not work with large collections, with multiple partitions.

**Comment by khdang** [comment]
@Nican thanks for letting us know about this. 
This is related a to [known issue](https://github.com/Azure/azure-cosmosdb-spark/issues/84) that has been fixed in the latest release 0.0.4. It affects data with short names. Can you try again the latest jars? If you still have this issue please let us know.

**Comment by Nican** [comment]
Issued is resolved. :) 

As a side note: 
1. the notebook should be updated
2. the folder in the "releases" directory has versions out of order. "2.1.0_2.11-0.0.4" vs "0.04-2.1.0_2.11"
3. the release has too many jar files, and they do not work together. There needs to be clarification on which ones to use.

**Comment by khdang** [comment]
Thanks for the feedbacks, Nican! We've noted and will take care of them.
