### ISSUE TITLE
PartitionKeyRange with id '47' in collection 'nNBlAJxbGgU=' doesn't exist.

### ISSUE THREAD

**Issue by timfpark** [Azure/azure-cosmosdb-spark#125]
During job execution, I suspect a partition split happened as the database was loaded with data, and the following exception occurred:

17/09/06 22:43:15 WARN TaskSetManager: Lost task 37.0 in stage 4.0 (TID 155, 10.244.3.5, executor 3): java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: PartitionKeyRange with id '47' in collection 'nNBlAJxbGgU=' doesn't exist.
ActivityId: 0cc77f62-61b9-43b0-80bd-0950ac76c500, StatusCode: InvalidPartition
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:86)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:33)
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.next(ProxyQueryExecutionContext.java:151)
	at com.microsoft.azure.documentdb.internal.query.ProxyQueryExecutionContext.next(ProxyQueryExecutionContext.java:9)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at com.microsoft.azure.cosmosdb.spark.rdd.CosmosDBRDDIterator.next(CosmosDBRDDIterator.scala:332)
	at com.microsoft.azure.cosmosdb.spark.rdd.CosmosDBRDDIterator.next(CosmosDBRDDIterator.scala:117)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:120)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:112)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:112)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:509)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:333)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
Caused by: com.microsoft.azure.documentdb.DocumentClientException: PartitionKeyRange with id '47' in collection 'nNBlAJxbGgU=' doesn't exist.
ActivityId: 0cc77f62-61b9-43b0-80bd-0950ac76c500, StatusCode: InvalidPartition
	at com.microsoft.azure.documentdb.internal.ErrorUtils.maybeThrowException(ErrorUtils.java:69)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.performPostRequest(GatewayProxy.java:279)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.doQuery(GatewayProxy.java:129)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.processMessage(GatewayProxy.java:343)
	at com.microsoft.azure.documentdb.DocumentClient$10.apply(DocumentClient.java:3021)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:58)
	at com.microsoft.azure.documentdb.DocumentClient.doQuery(DocumentClient.java:3027)
	at com.microsoft.azure.documentdb.DocumentQueryClientInternal.doQuery(DocumentQueryClientInternal.java:40)
	at com.microsoft.azure.documentdb.internal.query.AbstractQueryExecutionContext.executeRequest(AbstractQueryExecutionContext.java:214)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.executeOnce(DefaultQueryExecutionContext.java:137)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.fillBuffer(DefaultQueryExecutionContext.java:101)
	at com.microsoft.azure.documentdb.internal.query.DefaultQueryExecutionContext.next(DefaultQueryExecutionContext.java:84)
	... 20 more

**Comment by khdang** [comment]
Thanks, Tim. I think this is related to https://github.com/Azure/azure-cosmosdb-spark/issues/116 which happens due to partition split.

**Comment by mikaseb02** [comment]
Is there a solution? 
I'm the same problem...

**Comment by nomiero** [comment]
Split is currently handled by the connector
