### ISSUE TITLE
collection connection fails with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by martenlindblad** [Azure/azure-cosmosdb-spark#136]
Trying to connect to a collection works great until it is loaded with some data.
The data is coming from two iot devices via Streaming Analytics.
I have 10GB 400 RU at the moment, but I tried increasing to no avail. 
It's only about 20 MB of data in the collection at the moment.
```
// Import Necessary Libraries
import org.joda.time._
import org.joda.time.format._
import com.microsoft.azure.cosmosdb.spark.schema._
import com.microsoft.azure.cosmosdb.spark._
import com.microsoft.azure.cosmosdb.spark.config.Config

// Configure connection to your collection
val readConfig2 = Config(Map("Endpoint" -> "https://yyy.documents.azure.com:443/",
"Masterkey" -> "xxx",
"Database" -> "iot",
"Collection" -> "steps"))

// Create collection connection
val coll = spark.sqlContext.read.cosmosDB(readConfig2)
coll.createOrReplaceTempView("c")
```

The error I get is:
17/10/24 06:53:27 ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 2)
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.TypeCoercion$.findTightestCommonTypeOfTwo()Lscala/Function2;
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBSchema$$compatibleType(CosmosDBSchema.scala:112)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:66)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:66)
        at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:189)
        at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:188)
        at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:150)
        at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
17/10/24 06:53:27 WARN TaskSetManager: Lost task 0.0 in stage 4.0 (TID 2, localhost, executor driver): java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.TypeCoercion$.findTightestCommonTypeOfTwo()Lscala/Function2;
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBSchema$$compatibleType(CosmosDBSchema.scala:112)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:66)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:66)
        at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:189)
        at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:188)
        at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:150)
        at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

17/10/24 06:53:27 ERROR TaskSetManager: Task 0 in stage 4.0 failed 1 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 2, localhost, executor driver): java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.TypeCoercion$.findTightestCommonTypeOfTwo()Lscala/Function2;
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBSchema$$compatibleType(CosmosDBSchema.scala:112)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:66)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:66)
        at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:189)
        at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:188)
        at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:150)
        at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2119)
  at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1115)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1108)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema.schema(CosmosDBSchema.scala:68)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBRelation$$lazySchema$lzycompute(CosmosDBRelation.scala:59)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBRelation$$lazySchema(CosmosDBRelation.scala:44)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation$$anonfun$schema$1.apply(CosmosDBRelation.scala:62)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation$$anonfun$schema$1.apply(CosmosDBRelation.scala:62)
  at scala.Option.getOrElse(Option.scala:121)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation.schema$lzycompute(CosmosDBRelation.scala:62)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRelation.schema(CosmosDBRelation.scala:62)
  at org.apache.spark.sql.execution.datasources.LogicalRelation$.apply(LogicalRelation.scala:77)
  at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:415)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
  at com.microsoft.azure.cosmosdb.spark.schema.DataFrameReaderFunctions.createDataFrame(DataFrameReaderFunctions.scala:104)
  at com.microsoft.azure.cosmosdb.spark.schema.DataFrameReaderFunctions.createCosmosDBDataFrame(DataFrameReaderFunctions.scala:136)
  at com.microsoft.azure.cosmosdb.spark.schema.DataFrameReaderFunctions.cosmosDB(DataFrameReaderFunctions.scala:60)
  ... 56 elided
Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.TypeCoercion$.findTightestCommonTypeOfTwo()Lscala/Function2;
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBSchema$$compatibleType(CosmosDBSchema.scala:112)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:66)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:66)
  at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:189)
  at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:188)
  at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:150)
  at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
  at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
  at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
  at org.apache.spark.scheduler.Task.run(Task.scala:108)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

**Comment by khdang** [comment]
@martenlindblad This error indicates that you may be using the Spark Connector for Spark 2.2, while your Spark cluster is on version < 2.2. Can you check and make sure the connector version you're using is compiled with right Spark version?

**Comment by martenlindblad** [comment]
I'm using a local standalone Spark 2.2.0-installation! Sorry, will close this issue!
