### ISSUE TITLE
scala.MatchError: null while trying to read a null value.

### ISSUE THREAD

**Issue by rajeevsinghAD** [Azure/azure-cosmosdb-spark#167]
Trying to read a collection using following spark sql. 
sqlContext.read.schema(<some schema>).cosmosDB(readConfig)
Here I am providing schema using schema() method on dataFrameReader and one of the field (say orderNum)is of type Long. One of the document has value **null** for orderNum. Spark job fails with scala.MatchError: null. 

This issue occurs for all data types expect Integer and String for both read operation and write operation

18/03/14 10:06:38 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, 10.75.169.35, executor 1): scala.MatchError: null (of class cosmosdb_connector_shaded.org.json.JSONObject$Null)
	at com.microsoft.azure.cosmosdb.spark.schema.JsonSupport$class.com$microsoft$azure$cosmosdb$spark$schema$JsonSupport$$toLong(JsonSupport.scala:104)
	at com.microsoft.azure.cosmosdb.spark.schema.JsonSupport$$anonfun$enforceCorrectType$1.apply(JsonSupport.scala:55)
	at scala.Option.map(Option.scala:146)
	at com.microsoft.azure.cosmosdb.spark.schema.JsonSupport$class.enforceCorrectType(JsonSupport.scala:47)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$.enforceCorrectType(CosmosDBRowConverter.scala:59)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$toSQL$1.apply(CosmosDBRowConverter.scala:116)
	at scala.Option.map(Option.scala:146)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$.toSQL(CosmosDBRowConverter.scala:95)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$1$$anonfun$apply$5.apply(CosmosDBRowConverter.scala:89)
	at scala.Option.map(Option.scala:146)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$1.apply(CosmosDBRowConverter.scala:89)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$1.apply(CosmosDBRowConverter.scala:80)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$.recordAsRow(CosmosDBRowConverter.scala:80)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$asRow$1.apply(CosmosDBRowConverter.scala:66)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$asRow$1.apply(CosmosDBRowConverter.scala:65)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.foreach(WholeStageCodegenExec.scala:375)
	at org.apache.spark.sql.hive.SparkHiveWriterContainer.writeToFile(hiveWriterContainers.scala:184)
	at org.apache.spark.sql.hive.execution.InsertIntoHiveTable$$anonfun$saveAsHiveFile$3.apply(InsertIntoHiveTable.scala:159)
	at org.apache.spark.sql.hive.execution.InsertIntoHiveTable$$anonfun$saveAsHiveFile$3.apply(InsertIntoHiveTable.scala:159)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rajeevsinghAD** [comment]
This issue occurs for all data types expect Integer and String for both read operation and write operation

**Comment by jpsimen** [comment]
I have the exact same problem. Is there some work-around?
I am using azure-cosmosdb-spark_2.2.0_2.11:1.1.1

**Comment by tknandu** [comment]
Fixed - We've released new version of the Cosmos DB Spark connector targeting Spark 2.3 on Maven (https://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-cosmosdb-spark_2.3.0_2.11%7C1.2.0%7Cjar)

**Comment by ShatabdM** [comment]
@tknandu But we . need this fix for spark 2.2.
Please suggest workarounds if any . if I need to work with 2.2 version

**Comment by lcmarques** [comment]
Is this still a bug for Spark 2.4 and Databricks? It seems that i've found exactly the same issue
