### ISSUE TITLE
CosmosDB configuration

### ISSUE THREAD

**Issue by lcaouen** [Azure/azure-cosmosdb-spark#195]
I'm trying to connect to a cosmosDB database. I'm using your sample code
```
import org.apache.spark.sql.{SparkSession}
import com.microsoft.azure.cosmosdb.spark.schema._
import com.microsoft.azure.cosmosdb.spark._
import com.microsoft.azure.cosmosdb.spark.config.Config

  val readConfig2 = Config(Map("Endpoint" -> "https://doctorwho.documents.azure.com:443/",
      "Masterkey" -> "le1n99i1w5l7uvokJs3RT5ZAH8dc3ql7lx2CG0h0kK4lVWPkQnwpRLyAN0nwS1z4Cyd1lJgvGUfMWR3v8vkXKA==",
      "Database" -> "DepartureDelays",
      "preferredRegions" -> "Central US;East US 2;",
      "Collection" -> "flights_pcoll",
      "SamplingRatio" -> "1.0"))

    // Create collection connection
    val coll = session.sqlContext.read.cosmosDB(readConfig2)
    coll.createOrReplaceTempView("c")
```

but I get the following error with the Config(Map line:

> Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
> 	at com.microsoft.azure.cosmosdb.spark.config.ConfigBuilder$$anon$1$$anonfun$1.apply(Config.scala:76)
> 	at com.microsoft.azure.cosmosdb.spark.config.ConfigBuilder$$anon$1$$anonfun$1.apply(Config.scala:76)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
> 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
> 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
> 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
> 	at com.microsoft.azure.cosmosdb.spark.config.ConfigBuilder$$anon$1.<init>(Config.scala:76)
> 	at com.microsoft.azure.cosmosdb.spark.config.ConfigBuilder.build(Config.scala:74)
> 	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:261)
> 	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:240)
> 	at fr.pj.digitalAdvertising.cosmosReader.read(cosmosReader.scala:13)
> 	at fr.pj.digitalAdvertising.planSearch$delayedInit$body.apply(planSearch.scala:35)
> 	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
> 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
> 	at scala.App$$anonfun$main$1.apply(App.scala:71)
> 	at scala.App$$anonfun$main$1.apply(App.scala:71)
> 	at scala.collection.immutable.List.foreach(List.scala:318)
> 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
> 	at scala.App$class.main(App.scala:71)
> 	at fr.pj.digitalAdvertising.planSearch$.main(planSearch.scala:5)
> 	at fr.pj.digitalAdvertising.planSearch.main(planSearch.scala)

I'm using this library
```
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.2.0",
  "org.apache.spark" %% "spark-sql" % "2.2.0",
  "org.mongodb.spark" %% "mongo-spark-connector" % "2.2.2",
  "com.microsoft.azure" % "azure-cosmosdb-spark_2.2.0_2.11" % "1.1.1"
)
```
what's wrong?

**Comment by mganta** [comment]
Whats your scala version?

**Comment by lcaouen** [comment]
I've finally found the problem. It was due to the library version and the scala version.
It's a pity we don't find any sbt configuration as the cosmos db version is not compatible with all the spark versions.
Here is my build.sbt to make it work:

```
scalaVersion := "2.10.7"


libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.2.0",
  "org.apache.spark" %% "spark-sql" % "2.2.0",
  "org.mongodb.spark" %% "mongo-spark-connector" % "2.2.2",
  "com.microsoft.azure" % "azure-cosmosdb-spark_2.2.0_2.10" % "1.0.0"
)

```
