### ISSUE TITLE
Bulk Write fails with dependency issue

### ISSUE THREAD

**Issue by mganta** [Azure/azure-cosmosdb-spark#197]
**Spark connector version: azure-cosmosdb-spark_2.2.0_2.11-1.1.0
Spark Version: Spark 2.2.0 Scala 2_11
Environment: Azure Databricks**

Bulk write fails with a dependency error **java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsed()Ljava/time/Duration;**

A simple call to write to cosmosdb with a writeconfig

```
val writeConfig = Config(Map(
     "Endpoint" -> "https://foo.documents.azure.com:443/",
     "Masterkey" -> "mysecret",
     "Database" -> "mydatabase",
     "PreferredRegions" -> "West US;East US;",
     "Collection" -> "mydata", 
     "SamplingRatio" -> "1.0",
     "BulkImport" -> "true",
     "WritingBatchSize" -> "1000",
     "ConnectionMaxPoolSize" -> "100",
     "Upsert" ->  "true"
))
```
Here is the full stack
```
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsed()Ljava/time/Duration;
	at com.microsoft.azure.documentdb.bulkexecutor.DocumentBulkExecutor.executeBulkImportAsyncImpl(DocumentBulkExecutor.java:619)
	at com.microsoft.azure.documentdb.bulkexecutor.DocumentBulkExecutor.executeBulkImportInternal(DocumentBulkExecutor.java:479)
	at com.microsoft.azure.documentdb.bulkexecutor.DocumentBulkExecutor.importAll(DocumentBulkExecutor.java:445)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$bulkImport$1.apply(CosmosDBSpark.scala:257)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$bulkImport$1.apply(CosmosDBSpark.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.bulkImport(CosmosDBSpark.scala:241)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.savePartition(CosmosDBSpark.scala:439)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.com$microsoft$azure$cosmosdb$spark$CosmosDBSpark$$saveFilePartition(CosmosDBSpark.scala:343)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:183)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:177)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:853)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:853)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:332)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:296)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by tknandu** [comment]
Are you using the uber jar from Maven (https://search.maven.org/remotecontent?filepath=com/microsoft/azure/azure-cosmosdb-spark_2.2.0_2.11/1.1.1/azure-cosmosdb-spark_2.2.0_2.11-1.1.1-uber.jar)?

**Comment by mganta** [comment]
I am supplying the maven coordinates to load up the driver and dependencies as a library in Azure databricks

**Comment by mganta** [comment]
I will try with the uber jar

**Comment by tknandu** [comment]
We've noticed an issue with providing Maven coordinates (shading issue with one of the dependencies). Will fix that soon

**Comment by pas725** [comment]
Using Uber jar(**azure-cosmosdb-spark_2.2.0_2.11-1.1.1-uber.jar**) fixed the issue.
On the Databricks you may need to restart the cluster after attaching library.

**Comment by tknandu** [comment]
We've released new version of the Cosmos DB Spark connector targeting Spark 2.3 on Maven (https://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-cosmosdb-spark_2.3.0_2.11%7C1.2.0%7Cjar)
