### ISSUE TITLE
Issue reading stream on databricks.

### ISSUE THREAD

**Issue by chmitch** [Azure/azure-cosmosdb-spark#208]
I've tried several permutations, even got as simple as a collection with exceptionally simple documents.  The only way I can get the readStream command to succeed is if the collection is empty.

Here is the stack trace I get:
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBSchema$$compatibleType(CosmosDBSchema.scala:115)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:67)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBSchema$$anonfun$3.apply(CosmosDBSchema.scala:67)
	at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:189)
	at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:188)
	at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:150)
	at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1677)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1665)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1664)

**Comment by tknandu** [comment]
@chmitch Can you please specify which Spark runtime version you are using as well as which version of our Spark connector you're using?

**Comment by tknandu** [comment]
We've released new version of the Cosmos DB Spark connector targeting Spark 2.3 on Maven (https://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-cosmosdb-spark_2.3.0_2.11%7C1.2.0%7Cjar)
