### ISSUE TITLE
error writing timestamp field to cosmosdb

### ISSUE THREAD

**Issue by liupeirong** [Azure/azure-cosmosdb-spark#240]
Getting the following error when trying to write a Spark dataframe with a field of Spark SQL TimestampType to Cosmos DB in Scala:

_java.lang.ClassCastException: java.lang.Long cannot be cast to java.sql.Timestamp_

If I cast the field to String, it works.

**Comment by tknandu** [comment]
@liupeirong Could you please paste the stack trace?

**Comment by liupeirong** [comment]
Here you go:

Stage 1003:>                                                       (0 + 2) / 2]18/08/23 23:08:52 WARN TaskSetManager: Lost task 0.0 in stage 1003.0 (TID 2008, wn0-pliusp.p42l3d32serefgaclbznrqafrc.xx.internal.cloudapp.net, executor 2): java.lang.ClassCastException: java.lang.Long cannot be cast to java.sql.Timestamp
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBRowConverter$$convertToJson(CosmosDBRowConverter.scala:156)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$internalRowToJSONObject$1.apply(CosmosDBRowConverter.scala:136)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$internalRowToJSONObject$1.apply(CosmosDBRowConverter.scala:134)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$.internalRowToJSONObject(CosmosDBRowConverter.scala:134)
        at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask$$anonfun$importStreamingData$1.apply(StreamingUtils.scala:74)
        at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask$$anonfun$importStreamingData$1.apply(StreamingUtils.scala:72)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask.importStreamingData(StreamingUtils.scala:72)
        at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink$$anonfun$addBatch$2.apply(CosmosDBSink.scala:49)
        at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink$$anonfun$addBatch$2.apply(CosmosDBSink.scala:47)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by manishsat** [comment]
Any solution??

**Comment by nomiero** [comment]
Can you send us a repro spark notebook with a sample json for us to investigate ?

**Comment by ttelfer** [comment]
Any solution? I've also ran into this bug.
