### ISSUE TITLE
Unable to write data with uber jar 1.2.7 due to com.google.guava dependency hell

### ISSUE THREAD

**Issue by AssafNeufeld** [Azure/azure-cosmosdb-spark#265]
Hi,

I'm using spark "2.3.0" on an Azure Databricks cluster.
and the cosmos db uber jar latest: "spark_2.3.0_2.11:1.2.7"

I'm trying to write (upsert) data into a collection with the following config:

```
      "Endpoint" -> s"https://$cosmosDbName:443/",
      "Masterkey" -> masterKey,
      "Database" -> database,
      "Collection" -> collection,
      "SamplingRatio" -> "1.0",
      "WritingBatchSize" -> "1000",
      "BulkImport" -> "true",
      "ConnectionMaxPoolSize" -> "100",
      "Upsert" ->  "true"


data.write.mode(SaveMode.Append).cosmosDB(config)
```

I keep running into the error:

> java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsed()Ljava/time/Duration;
> 	at com.microsoft.azure.documentdb.bulkexecutor.DocumentBulkExecutor.executeBulkImportAsyncImpl(DocumentBulkExecutor.java:692)
> 	at com.microsoft.azure.documentdb.bulkexecutor.DocumentBulkExecutor.executeBulkImportInternal(DocumentBulkExecutor.java:535)
> 	at com.microsoft.azure.documentdb.bulkexecutor.DocumentBulkExecutor.importAll(DocumentBulkExecutor.java:479)

This is due to the fact that this method is only available in guava 22.0 (a dependency of bulk executor), but Spark 2.3.0 provides version 16.0.1.

I tried avoiding this using Maven shading:

```
<executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>
                    shade
                </goal>
            </goals>
        </execution>
    </executions>

    <configuration>
        <minimizeJar>true</minimizeJar>
        <shadedArtifactAttached>true</shadedArtifactAttached>
        <shadedClassifierName>fat</shadedClassifierName>

        <relocations>
            <relocation>
                <pattern>com.google</pattern>
                <shadedPattern>shaded.guava</shadedPattern>
                <includes>
                    <include>com.google.**</include>
                </includes>

                <excludes>
                    <exclude>com.google.common.base.Optional</exclude>
                    <exclude>com.google.common.base.Absent</exclude>
                    <exclude>com.google.common.base.Present</exclude>
                </excludes>
            </relocation>
        </relocations>

        <filters>
            <filter>
                <artifact>*:*</artifact>
                <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                </excludes>
            </filter>
        </filters>

    </configuration>
</plugin>
```

But then run into this error, for a method that was deprecated in Guava version 22.0! :(

>  java.lang.NoClassDefFoundError: shaded/guava/common/util/concurrent/AsyncCallable

> 	at com.microsoft.azure.cosmosdb.spark.CosmosDBConnection.getDocumentBulkImporter(CosmosDBConnection.scala:95)
> 	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.bulkImport(CosmosDBSpark.scala:272)
> 	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.savePartition(CosmosDBSpark.scala:465)

I'm lost... Any idea what the issue is?

**Comment by AssafNeufeld** [comment]
Another thing (if anybody is facing the same issue) - what fixes this partially, is putting the cosmosdb maven dependency:

  

>       <dependency>
>             <groupId>com.microsoft.azure</groupId>
>             <artifactId>azure-cosmosdb-spark_2.3.0_2.11</artifactId>
>             <version>1.2.7</version>
>         </dependency>

First in the pom.xml !

The JAR then runs smoothly on the spark cluster, but fails locally (in intellij) due to local Spark unable to start...
