### ISSUE TITLE
Error when trying upsert cosmosDB

### ISSUE THREAD

**Issue by merinkumar** [Azure/azure-cosmosdb-spark#273]
When running the below code for upsert getting the error "Conflicting request to resource has been attempted. Retry to avoid conflicts.". If I delete all the documents in the collection and run the code, it inserts a new record (no issue there). But If i execute the same code again it fails.

We are using this setup:
JAR : azure-cosmosdb-spark_2.3.0_2.11-1.2.2-uber.jar
DataBricks Runtime: 4.3 (includes Apache Spark 2.3.1, Scala 2.11)
CosmosDB:
Database - mydb
Collection - customer (partition -> cid, unique key -> cid)
 
Notebook code:

import org.joda.time._
import org.joda.time.format._
import com.microsoft.azure.cosmosdb.spark.schema._
import com.microsoft.azure.cosmosdb.spark.CosmosDBSpark
import com.microsoft.azure.cosmosdb.spark.config.Config
import org.apache.spark.sql.functions._
import org.apache.spark.sql.{Row, SaveMode, SparkSession}

val configMap = Map(
  "Endpoint" -> "https://xxxxxxxxxxxx.documents.azure.com:443/",
  "Masterkey" -> "xxxxxxxxxxx",
  "Database" -> "mydb",
  "Collection" -> "customer",
  "query_custom" -> "SELECT 100 as cid, 'john' as firstname, 'raider' as lastname ",
  "preferredRegions" -> "North Europe",
  "Upsert" ->  "true"
)

val config = Config(configMap)
val df1 = spark.read.cosmosDB(config)
df1.show()
df1.write.mode(SaveMode.Overwrite)cosmosDB(config)

ERROR:
+---+---------+--------+
|cid|firstname|lastname|
+---+---------+--------+
|100|     john|  raider|
+---+---------+--------+

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 83.0 failed 4 times, most recent failure: Lost task 0.3 in stage 83.0 (TID 103, 10.139.64.5, executor 0): java.lang.Exception: Errors encountered in bulk import API execution. Exceptions observed:
[java.lang.RuntimeException: com.microsoft.azure.documentdb.DocumentClientException: {"Errors":["Conflicting request to resource has been attempted. Retry to avoid conflicts."]}
ActivityId: 5de9d65f-fa0b-11e8-914c-990954494fd0, Request URI: /apps/aaaec693-6930-4a12-8c46-8691847e6a8f/services/95775e69-5ede-45fc-9d65-5637fdbc39b7/partitions/b129d844-8981-4c5a-8e2c-946ba67a2c86/replicas/131886010901781220p//, StatusCode: RetryWith, SubStatusCode: ]
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.bulkImport(CosmosDBSpark.scala:309)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.savePartition(CosmosDBSpark.scala:465)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.com$microsoft$azure$cosmosdb$spark$CosmosDBSpark$$savePartition(CosmosDBSpark.scala:406)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:190)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:181)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:859)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:859)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:384)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rifuller** [comment]
I am also hitting this.  Unclear if it's a bug or my error.

```18/12/07 22:52:17 WARN GoneAndRetryWithRetryPolicy: Received retryWith exception, will retry
com.microsoft.azure.documentdb.DocumentClientException: {"Errors":["Conflicting request to resource has been attempted. Retry to avoid conflicts."]}
ActivityId: bed47346-fa72-11e8-8094-c5ddb4160d79, Request URI: /apps/a6ee72ae-40dd-4a37-9954-7efd9d5541d0/services/59845562-06ee-4e8c-9ab5-11c37be8de6e/partitions/deae23ff-fa6e-40c6-9e5d-de04baa53145/replicas/131884108785704779p//, StatusCode: RetryWith, SubStatusCode: 
	at com.microsoft.azure.documentdb.internal.ErrorUtils.maybeThrowException(ErrorUtils.java:74)
	at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.processResponse(HttpTransportClient.java:187)
	at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.invokeStore(HttpTransportClient.java:156)
	at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.invokeStore(HttpTransportClient.java:163)
	at com.microsoft.azure.documentdb.internal.directconnectivity.TransportClient.invokeResourceOperation(TransportClient.java:12)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ConsistencyWriter.writePrivate(ConsistencyWriter.java:105)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ConsistencyWriter.write(ConsistencyWriter.java:69)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ReplicatedResourceClient.invoke(ReplicatedResourceClient.java:66)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ServerStoreModel$1.apply(ServerStoreModel.java:103)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeStoreClientRequest(RetryUtility.java:133)
	at com.microsoft.azure.documentdb.internal.directconnectivity.ServerStoreModel.processMessage(ServerStoreModel.java:114)
	at com.microsoft.azure.documentdb.DocumentClient$4.apply(DocumentClient.java:3037)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:71)
	at com.microsoft.azure.documentdb.DocumentClient.doCreate(DocumentClient.java:3042)
	at com.microsoft.azure.documentdb.DocumentClient.executeStoredProcedure(DocumentClient.java:1578)
	at com.microsoft.azure.documentdb.bulkexecutor.internal.BatchInserter$1.call(BatchInserter.java:158)
	at com.microsoft.azure.documentdb.bulkexecutor.internal.BatchInserter$1.call(BatchInserter.java:130)```

**Comment by merinkumar** [comment]
Okay, got this solved, the issue is when upsetting, we need to have the system generated id field also in the data frame. Now it's working.

**Comment by rifuller** [comment]
My issue was I had multiple records in the same batch with the same id.

**Comment by Brucegx** [comment]
> Okay, got this solved, the issue is when upsetting, we need to have the system generated id field also in the data frame. Now it's working.

Hi we meet the same issue. Could I know what the system generated id field stand for? how could I set it?

**Comment by shkumesh** [comment]
Hi we meet the same issue. Could I know what the system generated id field stand for? how could I set it?
