### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.cosmosdb.spark.config.CosmosDBConfig

### ISSUE THREAD

**Issue by ggthename** [Azure/azure-cosmosdb-spark#319]
I'm using Azure Databricks Runtime 5.3 (includes Apache Spark 2.4.0, Scala 2.11) with azure-cosmosdb-spark_2.4.0_2.11-1.3.5.jar

I just tried to build a simple python example like this.
But It doesn't work. 
`%python
readConfig = {
  "Endpoint" : "https:///",
  "Masterkey" : "w==",
  "Database" : "outDatabase",
  "Collection" : "DeviceTelemetry",
  "query_custom" : "SELECT * FROM c"
}

flights = spark.read.format("com.microsoft.azure.cosmosdb.spark").options(**readConfig).load()
flights.count()`

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-4382541223346048> in <module>()
      6   "query_custom" : "SELECT * FROM c"
      7 }
----> 8 flights = spark.read.format("com.microsoft.azure.cosmosdb.spark").options(**readConfig).load()
      9 flights.count()

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    170             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    171         else:
--> 172             return self._df(self._jreader.load())
    173 
    174     @since(1.4)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o333.load.
: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.cosmosdb.spark.config.CosmosDBConfig$
	at com.microsoft.azure.cosmosdb.spark.config.CosmosDBConfigBuilder.<init>(CosmosDBConfigBuilder.scala:33)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:259)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:240)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:229)
	at com.microsoft.azure.cosmosdb.spark.DefaultSource.createRelation(DefaultSource.scala:55)
	at com.microsoft.azure.cosmosdb.spark.DefaultSource.createRelation(DefaultSource.scala:40)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:291)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:277)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cjsingh8512** [comment]
Please upgrade to the latest CosmsoDB spark connector. The issue must be resolved

**Comment by MNaveedKhalid** [comment]
I am also facing same issue and it is reproducible on latest version as well
https://mvnrepository.com/artifact/com.microsoft.azure/azure-cosmosdb-spark_2.0.2_2.11

**Comment by MNaveedKhalid** [comment]
Also note that - issue is reproducible only if jar file is installed on cluster, using maven coordinates, it works fine. I am using job clusters and they don't support maven - only jars can be installed!

**Comment by MNaveedKhalid** [comment]
Got the issue resolved, needed to get uber jar

**Comment by cjsingh8512** [comment]
Great! Let me know if you come across another issue
