### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.cosmosdb.spark.config.CosmosDBConfig using latest version 1.4

### ISSUE THREAD

**Issue by MNaveedKhalid** [Azure/azure-cosmosdb-spark#328]
I'm using Azure Databricks Cluster:  Standard_DS3_v2 - 5.5 (includes Apache Spark 2.4.*, Scala 2.11) with azure-azure-cosmosdb-spark_2.4.0_2.11-1.4.0.jar

I just tried to build a simple scala example like this.
But It doesn't work.
val readConfig = Map(
  "Endpoint" -> endpoint,
  "Masterkey" -> masterKey,
  "Database" -> "SampleCosmosDB",
  "Collection" -> "SampleCollection",
  "query_custom" -> sampleQuery
)

val dfTemp = spark.read.format("com.microsoft.azure.cosmosdb.spark").options(readConfig).load()
dfTemp.count()

Issue is also reported earlier and got closed.
https://github.com/Azure/azure-cosmosdb-spark/issues/319

**Comment by MNaveedKhalid** [comment]
Here is stack trace:

java.lang.NoClassDefFoundError: com/microsoft/azure/documentdb/ConnectionMode
	at com.microsoft.azure.cosmosdb.spark.config.CosmosDBConfig$.<init>(CosmosDBConfig.scala:134)
	at com.microsoft.azure.cosmosdb.spark.config.CosmosDBConfig$.<clinit>(CosmosDBConfig.scala)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:261)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:241)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:230)
	at com.microsoft.azure.cosmosdb.spark.DefaultSource.createRelation(DefaultSource.scala:55)
	at com.microsoft.azure.cosmosdb.spark.DefaultSource.createRelation(DefaultSource.scala:40)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:291)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:277)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:201)

Caused by: java.lang.ClassNotFoundException: com.microsoft.azure.documentdb.ConnectionMode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.microsoft.azure.cosmosdb.spark.config.CosmosDBConfig$.<init>(CosmosDBConfig.scala:134)
	at com.microsoft.azure.cosmosdb.spark.config.CosmosDBConfig$.<clinit>(CosmosDBConfig.scala)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:261)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:241)
	at com.microsoft.azure.cosmosdb.spark.config.Config$.apply(Config.scala:230)
	at com.microsoft.azure.cosmosdb.spark.DefaultSource.createRelation(DefaultSource.scala:55)
	at com.microsoft.azure.cosmosdb.spark.DefaultSource.createRelation(DefaultSource.scala:40)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:291)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:277)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:201)

**Comment by MNaveedKhalid** [comment]
Got the issue resolved, I was not using fat (uber) jar file and it missed dependency classes in it

**Comment by chrisrymer** [comment]
This link to databricks documentation show the solution.

https://kb.databricks.com/data-sources/cosmosdb-connector-lib-conf.html
