### ISSUE TITLE
NoSuchElementException without ConnectionMode with 1.4.1

### ISSUE THREAD

**Issue by algattik** [Azure/azure-cosmosdb-spark#338]
With azure-cosmosdb-spark_2.4.0_2.11-1.4.1-uber.jar running in Azure Databricks runtime 5.5, my job yields

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 6, 10.139.64.4, executor 1): java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at com.microsoft.azure.cosmosdb.spark.AsyncCosmosDBConnection.getClientConfiguration(AsyncCosmosDBConnection.scala:133)
	at com.microsoft.azure.cosmosdb.spark.AsyncCosmosDBConnection.asyncDocumentClient$lzycompute(AsyncCosmosDBConnection.scala:65)
	at com.microsoft.azure.cosmosdb.spark.AsyncCosmosDBConnection.asyncDocumentClient(AsyncCosmosDBConnection.scala:64)
	at com.microsoft.azure.cosmosdb.spark.AsyncCosmosDBConnection.createDocument(AsyncCosmosDBConnection.scala:127)
	at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask$$anonfun$importStreamingData$2.apply(StreamingUtils.scala:87)
	at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask$$anonfun$importStreamingData$2.apply(StreamingUtils.scala:79)
```	

With 1.4.0 it works without issue.

code (https://github.com/Azure-Samples/streaming-at-scale/blob/master/streaming/databricks/notebooks/eventhubs-to-cosmosdb.scala):

```
val cosmosDbConfig = Map(
  "Endpoint" -> dbutils.widgets.get("cosmosdb-endpoint"),
  "Masterkey" -> dbutils.secrets.get(scope = "MAIN", key = "cosmosdb-write-master-key"),
  "Database" -> dbutils.widgets.get("cosmosdb-database"),
  "Collection" -> dbutils.widgets.get("cosmosdb-collection")
)

streamDataMutated
  .writeStream
  .format(classOf[CosmosDBSinkProvider].getName)
  .option("checkpointLocation", "dbfs:/streaming_at_scale/checkpoints/streaming-cosmosdb")
  .outputMode("append")
  .options(cosmosDbConfig)
  .start()
```

Workaround: When adding
```
  "ConnectionMode" -> "DirectHttps",
```

the issue disappears

**Comment by FabianMeiswinkel** [comment]
This has been fixed in the [latest version](https://aka.ms/CosmosDB_OLTP_Spark_2.4_LKG)
