### ISSUE TITLE
Resource Not Found issue with bulk writing to a collection after recreating it

### ISSUE THREAD

**Issue by tritm78** [Azure/azure-cosmosdb-spark#414]
I wanted to ask if someone has also run into this issue and knows how to resolve it.

I'm using [azure-cosmos==3.1.0](https://github.com/Azure/azure-cosmos-python) python library to create/delete a collection and [azure-cosmosdb-spark==2.4.0](https://github.com/Azure/azure-cosmosdb-spark) for bulk writing to the collection. The bulk write would run fine and write data to a collection if the collection is created for the first time, but then would fail with "Resource Not Found" error after the collection is deleted and recreated. 

We have followed a few suggestions in the TSG "Resource Not Found" page by changing the consistency level to Strong and setting to not using Lazy indexing mode for creating collection, but still have no luck.

Here is the code to repro the issue:

```
import azure.cosmos.cosmos_client as cosmos_client

url_connection = "https://<endpoint>.documents.azure.com:443/"
master_key = "<master_key>"
database = "<database>"
database_link = "dbs/{0}".format(database)
container_id = "<collection_name>"

client = cosmos_client.CosmosClient(url_connection, {'masterKey': master_key})

# create container
partition_key = "Region"
coll = {"id": container_id, "partitionKey": {"paths": ["/{}".format(partition_key)], "kind": "Hash"}}
container = client.CreateContainer(database_link, coll)

# check if exists
collections = list(client.QueryContainers(database_link, {"query": "SELECT * FROM r where r.id=@id",
                                                          "parameters": [{"name": "@id", "value": container_id}]}))
if len(collections) >= 1:
  print("Collection with id {0} found.".format(container_id))

# bulk write
writeConfig = {
  'Endpoint' : url_connection,
  'Masterkey': master_key, 
  'Database': database, 
  'Collection': container_id, 
  'WritingBatchSize': 20, 
  'Upsert': 'true'
}

spark_df.write.mode("overwrite").format("com.microsoft.azure.cosmosdb.spark").options(**writeConfig).save()
 
# read to verify
readConfig = {
  "Endpoint" : url_connection,
  "Masterkey" : master_key, 
  "Database" : database,
  "Collection" : container_id,
  "query_custom" : "SELECT * FROM r"
}

spark_df_read = spark.read.format("com.microsoft.azure.cosmosdb.spark").options(**readConfig).load()
print(spark_df_read.count())

# delete container
collection_link = database_link + '/colls/{0}'.format(container_id)
client.DeleteContainer(collection_link)

# check NOT exists
collections = list(client.QueryContainers(database_link, {"query": "SELECT * FROM r where r.id=@id",
                                                          "parameters": [{"name": "@id", "value": container_id}]}))
if len(collections) <= 0:
  print("Collection with id {0} was deleted.".format(container_id))
  
# REcreate container
partition_key = "Region"
coll = {"id": container_id, "partitionKey": {"paths": ["/{}".format(partition_key)], "kind": "Hash"}}
container = client.CreateContainer(database_link, coll)

# bulk write
writeConfig = {
      'Endpoint' : url_connection,
      'Masterkey': master_key, 
      'Database': 'rcstoragetestshared', 
      'Collection': container_id, 
      'WritingBatchSize': 20, 
      'Upsert': 'true'
}

spark_df.write.mode("overwrite").format("com.microsoft.azure.cosmosdb.spark").options(**writeConfig).save()   <<<< would fail with "Resource Not Found"
```

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o1509.save.
: com.microsoft.azure.documentdb.DocumentClientException: Message: {"Errors":["Resource Not Found. Learn more: https:\/\/aka.ms\/cosmosdb-tsg-not-found"]}
ActivityId: ae09cf6d-6488-4d29-a63e-ea03369c3b11, Request URI: /apps/b94e1dc4-b993-4500-a764-037a124e0211/services/11bdfc79-7d83-4c41-ab9f-d9563325c386/partitions/61f78334-8ed4-4200-9119-c4983316ba85/replicas/132446550091647170s/, RequestStats: 
RequestStartTime: 2020-10-12T23:27:09.8848252Z, RequestEndTime: 2020-10-12T23:27:09.8948017Z,  Number of regions attempted:1
ResponseTime: 2020-10-12T23:27:09.8948017Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus1-fd38.documents.azure.com:14423/apps/b94e1dc4-b993-4500-a764-037a124e0211/services/11bdfc79-7d83-4c41-ab9f-d9563325c386/partitions/61f78334-8ed4-4200-9119-c4983316ba85/replicas/132446550091647170s/, LSN: 118920, GlobalCommittedLsn: 118920, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: -1#118920, UsingLocalLSN: True, TransportException: null, ResourceType: Collection, OperationType: Read
, SDK: Microsoft.Azure.Documents.Common/2.11.0, StatusCode: NotFound
	at com.microsoft.azure.documentdb.internal.ErrorUtils.maybeThrowException(ErrorUtils.java:74)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.performGetRequest(GatewayProxy.java:239)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.doRead(GatewayProxy.java:93)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.processMessage(GatewayProxy.java:363)
	at com.microsoft.azure.documentdb.DocumentClient$9.apply(DocumentClient.java:3117)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:74)
	at com.microsoft.azure.documentdb.DocumentClient.doRead(DocumentClient.java:3123)
	at com.microsoft.azure.documentdb.DocumentClient.readCollection(DocumentClient.java:760)

**Comment by yuzhangyi** [comment]
I meet the same issue, could you help have a look?

**Comment by FaCoffee1984** [comment]
Same issue for me.
