### ISSUE TITLE
I am trying to insert a streaming dataframe onto Cosmos from databricks but the streaming job is failing with Null pointer exception

### ISSUE THREAD

**Issue by venkdora** [Azure/azure-cosmosdb-spark#428]
Jar : azure_cosmosdb_spark_2_4_0_2_11_3_3_0_uber.jar

Cluster spark version - 2.4.3

Cluster scala version - 2.11

Readstream works(connecting to cosmos) 
write stream doesnt work

![image](https://user-images.githubusercontent.com/76182313/102536959-2f072400-405f-11eb-8e07-fca4aece0508.png)

at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBWriteStreamRetryPolicy$$anonfun$2.apply(CosmosDBWriteStreamRetryPolicy.scala:93) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBWriteStreamRetryPolicy$$anonfun$2.apply(CosmosDBWriteStreamRetryPolicy.scala:91) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBWriteStreamRetryPolicyUtil.lambda$ProcessWithRetries$5(CosmosDBWriteStreamRetryPolicyUtil.java:57) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowPath(OnSubscribeFromIterable.java:117) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89) at cosmosdb_connector_shaded.rx.Subscriber.setProducer(Subscriber.java:211) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeFlattenIterable$OnSubscribeScalarFlattenIterable.call(OnSubscribeFlattenIterable.java:351) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeFlattenIterable$OnSubscribeScalarFlattenIterable.call(OnSubscribeFlattenIterable.java:321) at cosmosdb_connector_shaded.rx.Observable.unsafeSubscribe(Observable.java:10327) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at cosmosdb_connector_shaded.rx.Observable.unsafeSubscribe(Observable.java:10327) at cosmosdb_connector_shaded.rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeReduceSeed.call(OnSubscribeReduceSeed.java:40) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeReduceSeed.call(OnSubscribeReduceSeed.java:24) at cosmosdb_connector_shaded.rx.Observable.unsafeSubscribe(Observable.java:10327) at cosmosdb_connector_shaded.rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at cosmosdb_connector_shaded.rx.Observable.subscribe(Observable.java:10423) at cosmosdb_connector_shaded.rx.Observable.subscribe(Observable.java:10390) at cosmosdb_connector_shaded.rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443) at cosmosdb_connector_shaded.rx.observables.BlockingObservable.last(BlockingObservable.java:226) at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask.importStreamingData(StreamingUtils.scala:87) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink$$anonfun$addBatch$4.apply(CosmosDBSink.scala:55) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink$$anonfun$addBatch$4.apply(CosmosDBSink.scala:53) at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:951) at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:951) at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2284) at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2284) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) at org.apache.spark.scheduler.Task.doRunTask(Task.scala:139) at org.apache.spark.scheduler.Task.run(Task.scala:112) at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:497) at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1526) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:503) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: cosmosdb_connector_shaded.rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: org.apache.spark.sql.catalyst.expressions.UnsafeRow.class at cosmosdb_connector_shaded.rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ... 41 more Driver stacktrace: at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2355) at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2343) at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2342) at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2342) at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1096) at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1096) at scala.Option.foreach(Option.scala:257) at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1096) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2574) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2522) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2510) at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49) at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:893) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2243) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2265) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2284) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2309) at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:951) at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:949) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112) at org.apache.spark.rdd.RDD.withScope(RDD.scala:379) at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:949) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink.addBatch(CosmosDBSink.scala:53) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$19.apply(MicroBatchExecution.scala:579) at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:111) at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:241) at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:97) at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:171) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:577) at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:251) at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:61) at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:576) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:207) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:175) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:175) at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:251) at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:61) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:175) at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56) at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:169) at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:296) at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:208) Caused by: java.lang.NullPointerException at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBWriteStreamRetryPolicy$$anonfun$2.apply(CosmosDBWriteStreamRetryPolicy.scala:93) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBWriteStreamRetryPolicy$$anonfun$2.apply(CosmosDBWriteStreamRetryPolicy.scala:91) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBWriteStreamRetryPolicyUtil.lambda$ProcessWithRetries$5(CosmosDBWriteStreamRetryPolicyUtil.java:57) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowPath(OnSubscribeFromIterable.java:117) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89) at cosmosdb_connector_shaded.rx.Subscriber.setProducer(Subscriber.java:211) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeFlattenIterable$OnSubscribeScalarFlattenIterable.call(OnSubscribeFlattenIterable.java:351) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeFlattenIterable$OnSubscribeScalarFlattenIterable.call(OnSubscribeFlattenIterable.java:321) at cosmosdb_connector_shaded.rx.Observable.unsafeSubscribe(Observable.java:10327) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at cosmosdb_connector_shaded.rx.Observable.unsafeSubscribe(Observable.java:10327) at cosmosdb_connector_shaded.rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeReduceSeed.call(OnSubscribeReduceSeed.java:40) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeReduceSeed.call(OnSubscribeReduceSeed.java:24) at cosmosdb_connector_shaded.rx.Observable.unsafeSubscribe(Observable.java:10327) at cosmosdb_connector_shaded.rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at cosmosdb_connector_shaded.rx.Observable.subscribe(Observable.java:10423) at cosmosdb_connector_shaded.rx.Observable.subscribe(Observable.java:10390) at cosmosdb_connector_shaded.rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443) at cosmosdb_connector_shaded.rx.observables.BlockingObservable.last(BlockingObservable.java:226) at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask.importStreamingData(StreamingUtils.scala:87) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink$$anonfun$addBatch$4.apply(CosmosDBSink.scala:55) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink$$anonfun$addBatch$4.apply(CosmosDBSink.scala:53) at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:951) at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:951) at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2284) at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2284) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) at org.apache.spark.scheduler.Task.doRunTask(Task.scala:139) at org.apache.spark.scheduler.Task.run(Task.scala:112) at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:497) at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1526) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:503) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: cosmosdb_connector_shaded.rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: org.apache.spark.sql.catalyst.expressions.UnsafeRow.class at cosmosdb_connector_shaded.rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) at cosmosdb_connector_shaded.rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)

**Comment by venkdora** [comment]
Issue is fixed by Microsoft in Latest jar version 3.6.4
