### ISSUE TITLE
Spark job starts failing with exception EOFException while reading changefeed

### ISSUE THREAD

**Issue by santosh-gupta11** [Azure/azure-cosmosdb-spark#436]
I am reading change feeds from cosmosDB. After running for sometime I start getting the below exception. Once this exception is thrown, any subsequent submits won't work and throw the same exception. 
Only after I delete all the files from the - ChangeFeedCheckpointLocation, I am able to submit again.

### Reader config - 
```
    val configMap = scala.collection.mutable.Map(
      "Endpoint" -> appConfig.cosmosDbEndpoint(),
      "MasterKey" -> appConfig.cosmosDbMasterKey(),
      "Database" -> appConfig.cosmosDbDatabaseName(),
      "Collection" -> appConfig.cosmosDbCollectionName(),
      "ReadChangeFeed" -> "true",
      "ChangeFeedQueryName" -> appName,
      "ChangeFeedStartFromTheBeginning" -> appConfig.startFromTheBeginning().toString(),
      "ChangeFeedUseNextToken" -> "true",
      "RollingChangeFeed" -> "true",
      "ChangeFeedCheckpointLocation" -> appConfig.changeFeedCheckpointLocation(),
      "ChangeFeedMaxPagesPerBatch" -> appConfig.changeFeedMaxPagesPerBatch().toString(),
      "ConnectionMode" -> appConfig.connectionMode(),
      "SamplingRatio" -> "1.0")
```
The value for ChangeFeedStartFromTheBeginning is true for the first run and switched to false after that.

### Exception:
> java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils$$anonfun$read$1.apply(HdfsUtils.scala:64)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils$$anonfun$read$1.apply(HdfsUtils.scala:62)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.retry(HdfsUtils.scala:131)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.read(HdfsUtils.scala:62)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.readChangeFeedToken(HdfsUtils.scala:122)
	at com.microsoft.azure.cosmosdb.spark.rdd.CosmosDBRDDIterator$.getCollectionTokens(CosmosDBRDDIterator.scala:89)
	at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSource.schema(CosmosDBSource.scala:100)
	at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSourceProvider.sourceSchema(CosmosDBSourceProvider.scala:51)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:209)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:95)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:95)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:33)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:171)
	at Workflows.Streaming.PROD.CosmosDbChangeFeedToCosomos.ChangeFeedProcessor$.main(ChangeFeedProcessor.scala:34)
	at Workflows.Streaming.PROD.CosmosDbChangeFeedToCosomos.ChangeFeedProcessor.main(ChangeFeedProcessor.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:759)

**Comment by revinjchalil** [comment]
Please use uber jar version >= 3.6.7 that has a fix for this issue.

**Comment by santosh-gupta11** [comment]
@revinjchalil 
I upgraded the version to 3.6.7 . I am still getting the same error. However the spark application does not terminates immediately on error after the upgrade. From the logs, it seems that in case of errors, we keep on retrying. I am getting the below logs repeatedly. Even after the retries, its not succeeding and has been stuck with this retries for hours.

>, retrying .. 
21/01/14 05:21:55 ERROR [Driver] util.HdfsUtils: Exception during executing HDFS operation with message: null and stacktrace: java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils$$anonfun$read$1.apply(HdfsUtils.scala:66)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils$$anonfun$read$1.apply(HdfsUtils.scala:64)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.retry(HdfsUtils.scala:150)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.retry(HdfsUtils.scala:157)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.retry(HdfsUtils.scala:157)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.retry(HdfsUtils.scala:157)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.retry(HdfsUtils.scala:157)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.read(HdfsUtils.scala:64)
	at com.microsoft.azure.cosmosdb.spark.util.HdfsUtils.readChangeFeedToken(HdfsUtils.scala:141)
	at com.microsoft.azure.cosmosdb.spark.rdd.CosmosDBRDDIterator$.getCollectionTokens(CosmosDBRDDIterator.scala:94)
	at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSource.schema(CosmosDBSource.scala:103)
	at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSourceProvider.sourceSchema(CosmosDBSourceProvider.scala:51)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:209)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:95)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:95)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:33)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:171)
	at Workflows.Streaming.PROD.CosmosDbChangeFeedToCosomos.ChangeFeedProcessor$.main(ChangeFeedProcessor.scala:34)
	at Workflows.Streaming.PROD.CosmosDbChangeFeedToCosomos.ChangeFeedProcessor.main(ChangeFeedProcessor.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:759)

**Comment by revinjchalil** [comment]
This exception is from reading empty checkpoint files that were created and left behind by the **prior** version jar executions. Please start fresh with new checkpoint path with 3.6.7

**Comment by santosh-gupta11** [comment]
I upgrade to uber 3.6.7.

Now I have started getting the below exception. While I did not see this exception with the same data with earlier versions or 3.6.7 sources jar.

>21/01/14 14:16:47 WARN [task-result-getter-0] scheduler.TaskSetManager: Lost task 35.0 in stage 4.0 (TID 931, CO4AAP1F2EC7C12, executor 4): scala.MatchError: null (of class org.json.JSONObject$Null)
	at com.microsoft.azure.cosmosdb.spark.schema.JsonSupport$class.com$microsoft$azure$cosmosdb$spark$schema$JsonSupport$$toDouble(JsonSupport.scala:115)
	at com.microsoft.azure.cosmosdb.spark.schema.JsonSupport$$anonfun$enforceCorrectType$1.apply(JsonSupport.scala:58)
	at scala.Option.map(Option.scala:146)
	at com.microsoft.azure.cosmosdb.spark.schema.JsonSupport$class.enforceCorrectType(JsonSupport.scala:48)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter.enforceCorrectType(CosmosDBRowConverter.scala:89)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$toSQL$1.apply(CosmosDBRowConverter.scala:182)
	at scala.Option.map(Option.scala:146)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter.toSQL(CosmosDBRowConverter.scala:156)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$2$$anonfun$apply$6.apply(CosmosDBRowConverter.scala:126)
	at scala.Option.map(Option.scala:146)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$2.apply(CosmosDBRowConverter.scala:126)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$2.apply(CosmosDBRowConverter.scala:116)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter.recordAsRow(CosmosDBRowConverter.scala:116)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$asRow$1.apply(CosmosDBRowConverter.scala:97)
	at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$asRow$1.apply(CosmosDBRowConverter.scala:95)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:216)
	at org.apache.spark.sql.execution.SortExec$$anonfun$1.apply(SortExec.scala:108)
	at org.apache.spark.sql.execution.SortExec$$anonfun$1.apply(SortExec.scala:101)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1381)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by santosh-gupta11** [comment]
The error in the last comment does not seems to be related with the version upgrade. Upgrading the version solves the initial issue. Hence closing the issue.
