### ISSUE TITLE
Saving to CosmosDB using read-only key has no error

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#92]
If saving a DataFrame using a read-only key, it looks like the Spark dataframe was saved to Cosmos DB but in fact nothing happened.  We need to push back the error to the Spark connector.

**Comment by khdang** [comment]
I'm trying reproduce this issue. In some cases it throws an error from the SDK: 

```scala
com.microsoft.azure.documentdb.DocumentClientException: {"Errors":["The MAC signature found in the HTTP request is not the same as the computed signature. Server used following string to sign - 'post\ndocs\ndbs\/DepartureDelays\/colls\/flights_pcoll_shadow\nthu, 03 aug 2017 23:10:43 gmt\n\n'"]}
ActivityId: b71adf71-4f94-44a5-ba11-fce0f5fc5f56, Request URI: /apps/5be3a0c4-25cc-4b2e-814d-b6396118d984/services/fd40e278-196a-4173-90d6-4dd2c24ffb76/partitions/7d24e1ea-7e36-405d-ab51-056221097af9/replicas/131462688043411192p//, StatusCode: Unauthorized
                at com.microsoft.azure.documentdb.internal.ErrorUtils.maybeThrowException(ErrorUtils.java:69)
                at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.processResponse(HttpTransportClient.java:151)
                at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.invokeStore(HttpTransportClient.java:121)
                at com.microsoft.azure.documentdb.internal.directconnectivity.HttpTransportClient.invokeStore(HttpTransportClient.java:128)
                at com.microsoft.azure.documentdb.internal.directconnectivity.TransportClient.invokeResourceOperation(TransportClient.java:12)
                at com.microsoft.azure.documentdb.internal.directconnectivity.ReplicatedResourceClient.write(ReplicatedResourceClient.java:76)
                at com.microsoft.azure.documentdb.internal.directconnectivity.ReplicatedResourceClient.invoke(ReplicatedResourceClient.java:51)
                at com.microsoft.azure.documentdb.internal.directconnectivity.ServerStoreModel$1.apply(ServerStoreModel.java:84)
                at com.microsoft.azure.documentdb.internal.RetryUtility.executeStoreClientRequest(RetryUtility.java:113)
                at com.microsoft.azure.documentdb.internal.directconnectivity.ServerStoreModel.processMessage(ServerStoreModel.java:89)
                at com.microsoft.azure.documentdb.DocumentClient$4.apply(DocumentClient.java:2900)
                at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:58)
                at com.microsoft.azure.documentdb.DocumentClient.doCreate(DocumentClient.java:2905)
                at com.microsoft.azure.documentdb.DocumentClient.access$100(DocumentClient.java:88)
                at com.microsoft.azure.documentdb.DocumentClient$1.apply(DocumentClient.java:761)
                at com.microsoft.azure.documentdb.internal.RetryUtility.executeCreateDocument(RetryUtility.java:163)
                at com.microsoft.azure.documentdb.DocumentClient.createDocument(DocumentClient.java:766)
                at com.microsoft.azure.documentdb.rx.internal.RxWrapperDocumentClientImpl$17.invoke(RxWrapperDocumentClientImpl.java:387)
                at com.microsoft.azure.documentdb.rx.internal.RxWrapperDocumentClientImpl$17.invoke(RxWrapperDocumentClientImpl.java:384)
                at com.microsoft.azure.documentdb.rx.internal.RxWrapperDocumentClientImpl$2.call(RxWrapperDocumentClientImpl.java:151)
                at com.microsoft.azure.documentdb.rx.internal.RxWrapperDocumentClientImpl$2.call(RxWrapperDocumentClientImpl.java:145)
                at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
                at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                at rx.Observable.unsafeSubscribe(Observable.java:10256)
                at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
```

**Comment by khdang** [comment]
Given there are error messages when writing with read-only key. I'm closing this until we have a repro.
